name: MAPS
channels:
    - conda-forge
dependencies:
    - python=3.6
    - numpy
    - pandas
    - jupyter
    - matplotlib
    - scipy
    - fiona
    - rasterio
    - cartopy
    - palettable
    - netcdf4
    - xarray
    - gridgeo
    - folium
    - mplleaflet
    - xlrd
